name: Bug Report
description: Create a report to help us reproduce and fix a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please search existing issues first.
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: Crash when exporting timeline
    validations: { required: true }
  - type: textarea
    id: system
    attributes:
      label: System information
      placeholder: |
        App version:
        OS/Platform:
        GPU (if relevant):
        Node/Python/Compiler:
    validations: { required: true }
  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: Add logs in triple backticks.
      placeholder: |
        What happened and where?
        ```
        # logs here
        ```
    validations: { required: true }
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. …
        2. …
        3. …
        ```bash
        # minimal repro / snippet
        ```
        Test data: [image](https://…), [model](https://…)
    validations: { required: true }
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: What should happen?
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      placeholder: What actually happens? (screenshots welcome)
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This is a bug report (not a question/feature).
          required: true
        - label: I searched docs/FAQ and existing issues.
          required: true
        - label: I tried the latest version and the bug persists.
        - label: I included a minimal repro and/or data.
